### ISSUE TITLE
"retweet" class causes Adblock to hide elements which use Entypo reshare icon

### ISSUE THREAD

**Issue by shmerl** [lwe/entypo-rails#17]
In diaspora* the issue came up with reshare icon being hidden by AdblockPlus because it uses "retweet" class as per https://github.com/lwe/entypo-rails/blob/master/app/assets/stylesheets/entypo.scss.erb#L143
See details on that issue [here](https://github.com/diaspora/diaspora/issues/6156).

Can it be renamed in entypo-rails to "reshare"? It's a more proper generic name for the class. "retweet" is too Twitter specific.

**Comment by lwe** [comment]
Hi @shmerl - yes, of course, can you provide a PR maybe?

**Comment by lwe** [comment]
Nevermind, added an alias named `reshare` - I don't think the whole CSS is blocked because it contains `retweet` somewhere correct? Can you test the current `3.0.0.pre.rc2`, thanks.

**Comment by shmerl** [comment]
Thanks. It's blocked as soon as some element has a retweet in the list of its classes. Probably diaspora can avoid using that, and use the "reshare" alias instead to work around it. I'll let you know how that works out.

**Comment by lwe** [comment]
Cool, thanks, let me know how it works out.

**Comment by shmerl** [comment]
It's working fine now in Diaspora.

**Comment by lwe** [comment]
👌 thanks for the update and glad it's now fixed somehow.
