### ISSUE TITLE
Rails 5 compatiblity

### ISSUE THREAD

**Issue by zedtux** [lwe/entypo-rails#19]
The stable release is limited to Rails 3 and the release candidate to Rails 4. Now that Rails 5 is the stable version, this gem cannot be used anymore.

Can you please fix this @lwe ?

**Comment by lwe** [comment]
Hey Guillaume, currently my time for working on entypo-rails is a bit
limited, sorry. However I'd happily merge a pull-request that provides
Rails 5 compatibility.

**Comment by piedoom** [comment]
I believe it's just a simple change in the gemspec.  https://github.com/lwe/entypo-rails/pull/20 fixed the issue for me.

**Comment by zedtux** [comment]
You are right @piedoom, but actually not specifying the upper version of Rails doesn't sound good to me (while it will work). Usually we set lower to 6.0 or lower or equal to 5.1. (Just to mention it :))

**Comment by zedtux** [comment]
And thank you by the way :)

**Comment by piedoom** [comment]
Thanks @zedtux - I'm admittedly not a pro when it comes to Rubygems.  Is setting the version < 6.0 to avoid conflicts with a new (potentially breaking) version of Railties?

**Comment by lwe** [comment]
Good idea, will add this 👍 release will follow next week

**Comment by zedtux** [comment]
Yes @piedoom, it's just to avoid having people installing the current version with Rails 6 (when it will be out) while this version is maybe not compatible with.

**Comment by lwe** [comment]
Thanks for all the work :tada:, just pushed version 3.0.0 to rubygems.

https://rubygems.org/gems/entypo-rails
